name: EnsDaire
version: '${project.version}'
main: org.byauth.EnsDaire
api-version: '1.20'
description: Daireden Son Çıkan Kazanır - EnsDaire Mini Game
authors: [Ensis]

commands:
  ensdaire:
    description: EnsDaire ana komutu
    aliases: [ed, daire]
    usage: /ensdaire <komut>
  katil:
    description: Bir arenaya katılır.
  ayril:
    description: Aktif arenadan ayrılır.
  kozmetik:
    description: Kozmetik menüsünü açar.
    aliases: [market, kozmetikler]
  destekle:
    description: İzleyiciyken açık olan oyuncuları desteklemeni sağlar.
    aliases: [destek]

permissions:
  ensdaire.play:
    description: Oyuna katılma izni
    default: true
  ensdaire.admin:
    description: Admin komutları
    default: op
  ensdaire.bypass:
    description: Oyun kısıtlamalarını atla
    default: op
